project:
  type: website
  output-dir: docs
  resources:
    - static/**

website:
  title: "Reactive Autonomous Racing with F1TENTH Car"
  navbar: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: full